# Generated by Django 5.1.4 on 2026-06-22 14:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("game_key", models.SlugField(max_length=64)),
                (
                    "study_set_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Optional: the study set this play drew its content from.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0)),
                (
                    "progress",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Opaque save-state blob for resume.",
                    ),
                ),
                (
                    "reward_points",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Points granted on completion (by the rewards engine).",
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="games.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="games_games_user_id_61dfaf_idx",
                    ),
                    models.Index(
                        fields=["user", "game_key", "status"],
                        name="games_games_user_id_55b9f3_idx",
                    ),
                ],
            },
        ),
    ]
