# Generated by Django 5.1.4 on 2026-06-22 15:27

import apps.games.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.SlugField(
                        help_text="Stable client id (LearningGame.id). Keep it unique across all games, e.g. 'quiz_rush'.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Path segment under the games base URL: {gamesBaseUrl}/games/<slug>/index.html",
                        max_length=64,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("description", models.CharField(max_length=200)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Material icon name (e.g. 'bolt'). Falls back to emoji, then a generic game icon, if unknown to the client.",
                        max_length=64,
                    ),
                ),
                ("emoji", models.CharField(blank=True, default="", max_length=8)),
                (
                    "cover_colors",
                    models.JSONField(
                        default=list,
                        help_text='Two-stop gradient, e.g. ["0xFFFBC78A", "0xFFEF4444"].',
                        validators=[apps.games.models._validate_cover_colors],
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=6,
                    ),
                ),
                (
                    "requires",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Data-driven canPlay rule, e.g. {"quiz": 1} or {"words": 2}. Empty means the game is always available.',
                        validators=[apps.games.models._validate_requires],
                    ),
                ),
                (
                    "min_app_version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hide from clients older than this semver (e.g. '1.4.0'). Blank means no minimum.",
                        max_length=16,
                    ),
                ),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower sorts first; ties broken by name."
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.AlterField(
            model_name="gamesession",
            name="game_key",
            field=models.SlugField(
                help_text="Stable registry id of the game (LearningGame.id / Game.key).",
                max_length=64,
            ),
        ),
    ]
