# Generated by Django 5.1.4 on 2026-06-22 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_game_alter_gamesession_game_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="audience",
            field=models.CharField(
                choices=[("stable", "Stable"), ("beta", "Beta")],
                db_index=True,
                default="stable",
                help_text="'beta' games are only returned when the client asks for the beta channel — use it to canary a game before going stable.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="max_score",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Server-side sanity cap on a play's score (0 = no cap). Guards leaderboards against tampered client-reported scores.",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="sdk_version",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="PlayStudy SDK version this bundle targets. Clients hide games whose sdkVersion is newer than the app supports.",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="version",
            field=models.SlugField(
                default="1",
                help_text="Immutable bundle version, used as a path segment (.../<slug>/<version>/). Bump it to deploy; point back to roll back.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="slug",
            field=models.SlugField(
                help_text="Path segment under the games base URL: {gamesBaseUrl}/games/<slug>/<version>/index.html",
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="GameTelemetry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("game_key", models.SlugField(max_length=64)),
                ("version", models.SlugField(blank=True, default="", max_length=32)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("loaded", "Loaded"),
                            ("load_failed", "Load failed"),
                            ("error", "Runtime error"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ("message", models.CharField(blank=True, default="", max_length=500)),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_telemetry",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["game_key", "kind", "-created_at"],
                        name="games_gamet_game_ke_81af08_idx",
                    )
                ],
            },
        ),
    ]
