# Generated by Django 5.1.4 on 2026-05-23 20:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("studysets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("material_title", models.CharField(max_length=255)),
                ("exam_title", models.CharField(max_length=255)),
                ("exam_date", models.DateField()),
                ("questions_per_day", models.PositiveSmallIntegerField()),
                ("topics", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "study_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studysets.studyset",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="DailyResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ymd", models.CharField(max_length=10)),
                ("correct", models.PositiveSmallIntegerField()),
                ("total", models.PositiveSmallIntegerField()),
                ("completed", models.BooleanField(default=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="examprep.examplan",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="examplan",
            index=models.Index(
                fields=["owner", "-created_at"], name="examprep_ex_owner_i_21473b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyresult",
            constraint=models.UniqueConstraint(
                fields=("plan", "ymd"), name="unique_plan_day_result"
            ),
        ),
    ]
