# Generated by Django 5.1.4 on 2026-06-27 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examprep", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examplan",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="examplan",
            name="excluded_topics",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="examplan",
            name="frequency_multiplier",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="examplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("generating", "Generating"),
                    ("proposed", "Proposed"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                ],
                default="active",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="PlanDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ymd", models.CharField(max_length=10)),
                ("day_index", models.PositiveIntegerField()),
                ("section_index", models.PositiveIntegerField(default=0)),
                (
                    "section_title",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("question_ids", models.JSONField(default=list)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="examprep.examplan",
                    ),
                ),
            ],
            options={
                "ordering": ("day_index",),
                "indexes": [
                    models.Index(
                        fields=["plan", "ymd"], name="examprep_pl_plan_id_3d814c_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plan", "ymd"), name="unique_plan_day"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlanReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ymd", models.CharField(max_length=10)),
                ("kind", models.CharField(default="daily", max_length=16)),
                ("message", models.CharField(blank=True, default="", max_length=255)),
                ("emailed_at", models.DateTimeField(blank=True, null=True)),
                ("dismissed", models.BooleanField(default=False)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="examprep.examplan",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["plan", "ymd"], name="examprep_pl_plan_id_ebbde4_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plan", "ymd", "kind"), name="unique_plan_reminder"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WrongAnswerCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_id", models.UUIDField()),
                ("topic", models.CharField(default="General", max_length=120)),
                ("box", models.PositiveSmallIntegerField(default=1)),
                ("due_ymd", models.CharField(max_length=10)),
                ("times_wrong", models.PositiveIntegerField(default=0)),
                ("times_right", models.PositiveIntegerField(default=0)),
                ("resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="examprep.examplan",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["plan", "resolved", "due_ymd"],
                        name="examprep_wr_plan_id_33480c_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plan", "question_id"), name="unique_plan_card"
                    )
                ],
            },
        ),
    ]
