# Generated by Django 5.1.4 on 2026-05-23 20:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudySet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                (
                    "source_kind",
                    models.CharField(
                        choices=[("link", "Link"), ("file", "File"), ("text", "Text")],
                        max_length=8,
                    ),
                ),
                ("source_ref", models.TextField()),
                ("summary", models.TextField(blank=True, default="")),
                ("key_points", models.JSONField(default=list)),
                ("topics", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prompt", models.TextField()),
                ("choices", models.JSONField()),
                ("correct_index", models.PositiveSmallIntegerField()),
                ("explanation", models.TextField(blank=True, null=True)),
                ("topic", models.CharField(default="General", max_length=120)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "study_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz",
                        to="studysets.studyset",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="WordChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("word", models.CharField(max_length=64)),
                ("clue", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "study_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_game",
                        to="studysets.studyset",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
        migrations.AddIndex(
            model_name="studyset",
            index=models.Index(
                fields=["owner", "-created_at"], name="studysets_s_owner_i_713403_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studyset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("owner", "idempotency_key"),
                name="unique_owner_idempotency_key",
            ),
        ),
    ]
