# Generated by Django 5.1.4 on 2026-05-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studysets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studyset",
            name="sections",
            field=models.JSONField(default=list),
        ),
    ]
