# Generated by Django 5.1.4 on 2026-05-29 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("studysets", "0002_studyset_sections"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=8, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuardianLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardian_of",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardians",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("parent", "student"), name="unique_parent_student"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SectionProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_index", models.PositiveIntegerField()),
                (
                    "section_title",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("seconds_spent", models.PositiveIntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                ("quiz_correct", models.PositiveIntegerField(default=0)),
                ("quiz_total", models.PositiveIntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "study_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_progress",
                        to="studysets.studyset",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["student", "study_set"],
                        name="family_sect_student_800a8a_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "study_set", "section_index"),
                        name="unique_student_section",
                    )
                ],
            },
        ),
    ]
